apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect.git
    labels:
      app: boat-detect-notebook
      app.kubernetes.io/component: boat-detect-notebook
      app.kubernetes.io/instance: boat-detect-notebook
      app.kubernetes.io/part-of: detection
    name: boat-detect-notebook
    namespace: boats-demo
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: boat-detect-notebook:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /environment
      git:
        uri: https://github.com/redhat-naps-da/boat-detect.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 1
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect.git
    labels:
      app: boat-detect-builder
      app.kubernetes.io/component: boat-detect-builder
      app.kubernetes.io/instance: boat-detect-builder
      app.kubernetes.io/part-of: detection
    name: boat-detect-builder
    namespace: boats-demo
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: boat-detect-builder:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /builder
      git:
        uri: https://github.com/redhat-naps-da/boat-detect.git
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
  status:
    lastVersion: 1
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect/
    labels:
      app: boat-detect
      app.kubernetes.io/component: boat-detect
      app.kubernetes.io/instance: boat-detect
      app.kubernetes.io/name: python
      app.kubernetes.io/part-of: detection
      app.openshift.io/runtime: python
      app.openshift.io/runtime-version: 3.8-ubi8
    name: boat-detect
    namespace: boats-demo
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: boat-detect:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: /app
      git:
        uri: https://github.com/redhat-naps-da/boat-detect/
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: boat-detect-builder:latest
          namespace: boats-demo
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
