apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      app.openshift.io/vcs-ref: master
      app.openshift.io/vcs-uri: https://github.com/redhat-naps-da/boat-detect.git
    labels:
      app: boat-identify
      app.kubernetes.io/component: boat-identify
      app.kubernetes.io/instance: boat-identify
      app.kubernetes.io/part-of: detection
    name: boat-identify
    namespace: boats-demo
  spec:
    lookupPolicy:
      local: false
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
